//! Backend: lower the low-level move plan to RepRap/Marlin-flavored G-code.
//!
//! Emits per-segment extrusion (E from a volumetric flow model), retraction on travels, and
//! `;TYPE:` / `;WIDTH:` comments, so re-parsing the output recovers the same deposited material.

use crate::ir::lo::{Program, SegmentKind};
use crate::ir::RegionKind;
use std::fmt::Write;

/// Options controlling G-code emission.
#[derive(Clone, Copy, Debug)]
pub struct GcodeOptions {
    /// Filament diameter (mm) for the flow model that turns width×height×length into an E amount.
    pub filament_diameter_mm: f64,
    /// Retraction length (mm) applied before a travel and reversed before printing (0 disables).
    pub retraction_mm: f64,
    /// Travel feedrate (mm/min) for `G0` (0 omits the F word).
    pub travel_feedrate: i64,
    /// Print feedrate (mm/min) for the first `G1` of a run (0 omits the F word).
    pub print_feedrate: i64,
}

impl Default for GcodeOptions {
    fn default() -> Self {
        Self {
            filament_diameter_mm: 1.75,
            retraction_mm: 0.8,
            travel_feedrate: 9000,
            print_feedrate: 1800,
        }
    }
}

fn mm(um: i64) -> String {
    format!("{:.3}", um as f64 / 1000.0)
}

/// Emit G-code with default options.
pub fn to_gcode(program: &Program) -> String {
    to_gcode_with(program, &GcodeOptions::default())
}

/// Emit G-code with explicit options.
pub fn to_gcode_with(program: &Program, opts: &GcodeOptions) -> String {
    let filament_area = std::f64::consts::PI
        * (opts.filament_diameter_mm / 2.0)
        * (opts.filament_diameter_mm / 2.0);
    let mut out = String::new();
    out.push_str("; generated by kerf\nG21 ; units = mm\nG90 ; absolute XYZ\nM83 ; relative E\n");

    let mut prev_z: Option<i64> = None;
    let mut cur: Option<(i64, i64)> = None;
    let mut retracted = false;
    let mut last_role: Option<RegionKind> = None;
    let mut last_width: Option<i64> = None;

    for layer in &program.layers {
        let h_um = match prev_z {
            Some(pz) => (layer.z_um - pz).max(1),
            None => layer.z_um.max(1),
        };
        let h_mm = h_um as f64 / 1000.0;
        let _ = writeln!(
            out,
            ";LAYER_CHANGE\n;Z:{}\n;HEIGHT:{}",
            mm(layer.z_um),
            mm(h_um)
        );
        let _ = writeln!(out, "G0 Z{}", mm(layer.z_um));
        prev_z = Some(layer.z_um);

        for tp in &layer.toolpaths {
            let pts = &tp.path.points;
            let Some(&first) = pts.first() else { continue };
            let start = (first.x, first.y);

            match tp.kind {
                SegmentKind::Extrude(role) => {
                    if last_role != Some(role) {
                        let _ = writeln!(out, ";TYPE:{}", role_str(role));
                        last_role = Some(role);
                    }
                    if last_width != Some(tp.width_um) {
                        let _ = writeln!(out, ";WIDTH:{}", mm(tp.width_um));
                        last_width = Some(tp.width_um);
                    }
                    travel_to(&mut out, &mut cur, start, &mut retracted, opts);
                    if retracted {
                        let _ = writeln!(out, "G1 E{:.5}", opts.retraction_mm);
                        retracted = false;
                    }
                    let w_mm = tp.width_um as f64 / 1000.0;
                    // When the toolpath carries commanded flow (parsed from real G-code), emit that E
                    // total distributed by segment length, so re-parsing recovers the same E. Else
                    // fall back to the geometric volumetric model.
                    let total_len_mm: f64 = pts
                        .windows(2)
                        .map(|s| {
                            let dx = (s[1].x - s[0].x) as f64 / 1000.0;
                            let dy = (s[1].y - s[0].y) as f64 / 1000.0;
                            (dx * dx + dy * dy).sqrt()
                        })
                        .sum();
                    let mut first_seg = true;
                    for p in pts.iter().skip(1) {
                        let (px, py) = cur.unwrap_or(start);
                        let dx = (p.x - px) as f64 / 1000.0;
                        let dy = (p.y - py) as f64 / 1000.0;
                        let len = (dx * dx + dy * dy).sqrt();
                        let mut e = match tp.flow_e {
                            Some(total) if total_len_mm > 0.0 => total * (len / total_len_mm),
                            _ if filament_area > 0.0 => w_mm * h_mm * len / filament_area,
                            _ => 0.0,
                        };
                        // A moving extrude segment must emit an E the parser will read back as an
                        // extrude, or the re-parse turns it into a travel and the material is lost. The
                        // parser's threshold is EPS below the smallest 5-decimal E, so floor a nonzero
                        // move at 1e-5 mm. This can only *raise* a vanishingly small commanded flow
                        // (below G-code's own resolution) — occupancy round-trips; exact tiny-flow
                        // fidelity does not, which is already out of scope for the emitter.
                        if len > 0.0 && e < 1.0e-5 {
                            e = 1.0e-5;
                        }
                        let f = if first_seg && opts.print_feedrate > 0 {
                            format!(" F{}", opts.print_feedrate)
                        } else {
                            String::new()
                        };
                        let _ = writeln!(out, "G1 X{} Y{} E{e:.5}{f}", mm(p.x), mm(p.y));
                        cur = Some((p.x, p.y));
                        first_seg = false;
                    }
                }
                SegmentKind::Travel => {
                    let end = pts.last().map(|p| (p.x, p.y)).unwrap_or(start);
                    travel_to(&mut out, &mut cur, end, &mut retracted, opts);
                }
            }
        }
    }
    out
}

/// Emit a non-printing move to `target`, retracting first if configured (and not already retracted).
fn travel_to(
    out: &mut String,
    cur: &mut Option<(i64, i64)>,
    target: (i64, i64),
    retracted: &mut bool,
    opts: &GcodeOptions,
) {
    if *cur == Some(target) {
        return;
    }
    if opts.retraction_mm > 0.0 && !*retracted && cur.is_some() {
        let _ = writeln!(out, "G1 E-{:.5}", opts.retraction_mm);
        *retracted = true;
    }
    let f = if opts.travel_feedrate > 0 {
        format!(" F{}", opts.travel_feedrate)
    } else {
        String::new()
    };
    let _ = writeln!(out, "G0 X{} Y{}{f}", mm(target.0), mm(target.1));
    *cur = Some(target);
}

/// A `;TYPE:` string the parser's `classify_role` maps back to the same `RegionKind`.
fn role_str(r: RegionKind) -> &'static str {
    match r {
        RegionKind::Perimeter => "Perimeter",
        RegionKind::Infill => "Internal infill",
        RegionKind::Skin => "Solid infill",
        RegionKind::Support => "Support material",
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::ir::lo::{Layer, Toolpath};
    use crate::ir::{hi, Area, ExtrudePath, Point, Polyline, RegionKind};

    #[test]
    fn a_tiny_commanded_flow_extrude_still_round_trips_as_an_extrude() {
        // Regression: a very small flow_e distributed per segment used to emit E0.00000, which the
        // parser reads as a travel — silently losing the material. Every moving extrude segment must
        // emit an E the parser classifies as an extrude, so occupancy survives the round trip.
        let prog = Program {
            layers: vec![Layer {
                z_um: 200,
                toolpaths: vec![Toolpath {
                    kind: SegmentKind::Extrude(RegionKind::Perimeter),
                    path: Polyline::new(vec![
                        Point::new(0, 0),
                        Point::new(10_000, 0),
                        Point::new(10_000, 10_000),
                    ]),
                    width_um: 400,
                    flow_e: Some(1.0e-7), // absurdly small commanded flow
                }],
            }],
        };
        let reparsed = crate::frontend::parse(&to_gcode(&prog)).program;
        assert_eq!(
            crate::denote::denote_lo(&prog, 100),
            crate::denote::denote_lo(&reparsed, 100),
            "a tiny-flow extrude must not vanish into a travel on emit/re-parse",
        );
        assert_eq!(reparsed.extrusion_move_count(), 1);
    }

    #[test]
    fn emits_gcode_for_a_square() {
        let square = Polyline::new(vec![
            Point::new(0, 0),
            Point::new(20_000, 0),
            Point::new(20_000, 20_000),
        ]);
        let prog = Program {
            layers: vec![Layer {
                z_um: 200,
                toolpaths: vec![Toolpath {
                    kind: SegmentKind::Extrude(RegionKind::Perimeter),
                    path: square,
                    width_um: 400,
                    flow_e: None,
                }],
            }],
        };
        let g = to_gcode(&prog);
        assert!(g.contains("G0 Z0.200"));
        assert!(g.contains(";TYPE:Perimeter"));
        assert!(g.contains(";WIDTH:0.400"));
        assert!(g.contains("G1 X20.000 Y0.000 E"));
    }

    #[test]
    fn round_trip_preserves_denotation() {
        let path = |pts: Vec<(i64, i64)>| {
            Polyline::new(pts.into_iter().map(|(x, y)| Point::new(x, y)).collect())
        };
        let hi = hi::Program {
            layers: vec![
                hi::Layer {
                    z_um: 200,
                    regions: vec![hi::Region {
                        kind: RegionKind::Perimeter,
                        boundary: Area::default(),
                        fills: vec![ExtrudePath {
                            path: path(vec![
                                (0, 0),
                                (20_000, 0),
                                (20_000, 20_000),
                                (0, 20_000),
                                (0, 0),
                            ]),
                            width_um: 450,
                        }],
                    }],
                },
                hi::Layer {
                    z_um: 400,
                    regions: vec![hi::Region {
                        kind: RegionKind::Infill,
                        boundary: Area::default(),
                        fills: vec![ExtrudePath {
                            path: path(vec![(2000, 2000), (18_000, 18_000)]),
                            width_um: 400,
                        }],
                    }],
                },
            ],
        };
        let lo = crate::lower::lower(&hi);
        let reparsed = crate::frontend::parse(&to_gcode(&lo)).program;
        assert_eq!(
            crate::denote::denote_lo(&lo, 100),
            crate::denote::denote_lo(&reparsed, 100),
            "faithful backend must round-trip denotation",
        );
    }
}
